Shougo/neosnippet-snippets

neosnippets/rust.snip
Prefer
```rust
fn foo() { 
}
```
over
```rust
fn foo () {
}
```
See [rust guide](http://aturon.github.io/style/whitespace.html).
=> Why do some whitespaces following function name exist? (Rust)

neosnippets/systemverilog.snip, neosnippets/verilog.snip
Syntax systemverilog is not built-in,
but it can be found and downloaded easily
=> Add snippets for systemverilog and verilog

neosnippets/tex.snip
Just fixed typo of item in tex.snip, and added snippets that might be useful for beamer.
=> tex.snip: fix typo and add snippets for beamer

neosnippets/eruby.snip
When the cursor is immediately after the tag, neocomplete doesn't suggest snippet of eruby.
Procedure for reproducing
-------------------------
Use min.vim as vimrc, and edit test.erb
https://gist.github.com/pocke/15af0c621dd9ffd1c8a3
```sh
$ vim -u min.vim -N test.erb
```
Input `llllliru`.
Before patch, neocomplete doesn't suggest `ruby_code`, `ruby_print`, etc.
After patch, neocomplete suggests those.
=> Enable to work eruby snippet when the cursor is immediately after the tag

neosnippets/cs.snip
thanks ujihisa for appending option head.
sorry, but It has some problems.
- - -
private class<snip>
int Foo { get<snip>
if (foo) for<snip>
try {
foo;
} catch<snip>
try {
foo;
} finally<sni>
- - -
I fixed it.
sorry and thanks, Shougo and ujihisa.
=> Fixed cs.snip without option head in some patterns

neosnippets/rst.snip
Without this indentation, there will be no indentation after `C-k` move to content block when using `code_block` snippet.
=> [rst.snip] Add indentation in code_block

neosnippets/python.snip
The current `getattr` and `setattr` snippets don't work because the variable names are formatted incorrectly, `getattr` can only be used when preceded by whitespace (so for example `foo = func(getattr(obj, attr))` doesn't work), and `setattr` should take 3 arguments, not 2.
=> Fix Python get/set attr snipppets and add hasattr

neosnippets/_.snip
It seems the date snippets don't work properly. For some reason, when expanding `date_full`, the cursor does not end up at the end of the expanded text.
=> Add ${0} to date snippets

neosnippets/verilog.snip
In verilog, we usually declare the module name as its file name. So I think it's better to set the default module name as its file name.
=> Improve module declaration for verilog snippets

neosnippets/go.snip, neosnippets/go.vim
* add `${2}` so another jump escapes it
* fix whitespace after expanding
=> go: improve ife

neosnippets/scala.snip
Adds `cclass` which expands to `case class ..(..: ..)`
=> Add case class snippet for scala

neosnippets/ruby.snip
For example. When editing `foo_bar.rb`, neosnippet expands the following code as `class` snippet.
```ruby
class FooBar
end
```
In many cases, class name is camel cased filename in Ruby.
=> [Ruby] Suggest camel cased filename as a class name.

neosnippets/javascript.snip
Added ES2015 snippet ot javascript.snip
References: 
[Classes - JavaScript | MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Classes)
[import - Web Technology For Developers | MDN](https://developer.mozilla.org/en/docs/web/javascript/reference/statements/import)
=> Add support ES2015 to javascript.snip

neosnippets/go.snip
`pn` conflicts with snippet from [vim-go](https://github.com/fatih/vim-go/blob/10c805b83f160eb9e7f9cbe00d26c1b6d06ba636/gosnippets/snippets/go.snip#L249-L253), which stands for `panic`. So `pl` is safe for use.
Thanks for your time!
=> unconflict pn alias

neosnippets/go.vim
Improved golang snippet iferr creates placeholders available to jump to in place of strings returned from function.
Here is an example of unfolded iferr snippet for function returning some strings:
```
func foo() (string, bool, int, string, bool, error) {
if err != nil {
return "<`1`>", false, 0, "<`1`>", false, err<`0`>
}
}
```
One can easily fill some data inside quotes using placeholders.
=> Improved golang snippet iferr.

neosnippets/go.snip
Fix abbr in funcbench and funcTest
=> go.snip: Fix abbr in funcbench and funcTest

neosnippets/tex.snip
Consider single-escaped default placeholder(s) in a snippet, the second one `\\textwidth` in this commit.
Snippet candidate is shown as `\\textwidth`;  a backslash `\` vanishes and the default placeholder text is `\textwidth` when the snippet is expanded; another `\` vanishes after jump to it, resulting in `textwidth`.
Double-escape, `\\\textwidth`, is required to obtain `\textwidth` as default.
=> doubly escape backslash in default placeholder text

neosnippets/go.snip
Fix to follow naming convention.
"BenchmarkXxx" is correct, not "BenchXxx".
See https://golang.org/pkg/testing/#hdr-Benchmarks
=> Fix: go.snip

neosnippets/ada.snip
Two snippets have the same name, see https://github.com/Shougo/neosnippet-snippets/blob/5fadc11a40ff9e5c64371398c1752a1878377200/neosnippets/ada.snip#L110 and https://github.com/Shougo/neosnippet-snippets/blob/5fadc11a40ff9e5c64371398c1752a1878377200/neosnippets/ada.snip#L241
This PR fixes that.
=> ada.snip: Fix duplicate 'case' snippet

neosnippets/tex.snip
I added two additional math environments, namely:
```tex
$$ expression $$
```
and 
```tex
\[ expression \]
```
they all do the same as
```tex
\begin{equation*}
expression
\end{equation*}
```
but might be used by different users, including me.
=> Additional math environments for tex

neosnippets/ruby.snip
`{0}` is getting automatically added by neosnippets if it doesn't already exist.
In the case of the ruby snippets this was causing unwanted jumps to the end of for example method definitions.
This changes the ruby snippets to have `{0}` as their last marker
=> Use {0} marker as last marker for ruby snippets

neosnippets/asm.snip, neosnippets/c.snip
Extended C snippets with Doxygen style function documentation triggered using ```/**```.  This could be used for any high-level programming function documentation, e.g. Java, etc.  Maybe there is a better place to put this new documentation snippet to make it accessible to other languages also?
Added new assembly language Doxygen style function documentation triggered using ```;;```.
Both snippets use JavaDoc style ```@``` command format.  This is compliant with Doxygen:
[https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmd_intro](url)
=> Added new Doxygen style function documentation for C and assembly language

neosnippets/asm.snip, neosnippets/c.snip
Updated c and asm snippet triggers to ```doxy``` because the original triggers didn't work as they were interpreted as comments.  Also some minor formatting of snippet.
=> Updated c and asm snippet triggers

neosnippets/typescript.snip
`export default class SomeClass { ... }` is valid TypeScript code, and it is an useful idiom.
So I think the snippet should work after `export` keyword.
=> Work `class` and `interface` snip after `export` in TypeScript

neosnippets/c.snip
Create snippets for the use of malloc/calloc/realloc, also pairing the
first two with the corresponding free. Also add a similar snippet for
managing variable number of arguments in a function, from the creation
in the va_list to the destruction with va_end.
Also add some small snippets like scanf() or seed_rand()
Small changes in some other snippets, like a new alias for
_Static_assert(), no comma in printf to be like fprintf.
=> Memory management and variable arguments

neosnippets/c.snip, neosnippets/java.snip
Add "final" snippet to java, to create final non-static variables.
Use a placeholder at the end of #define instead of a trailing space.
Delete some unnecessary placeholders in single line snippets.
=> Final snippet and changing some placeholders

neosnippets/php.snip
Currently no `foreach` entry for PHP (existing entries: `pforeach`, `foreach-hashmap`, `foreach-list`).
I want `foreach` entry to expand to most generic foreach notation.
=> Add 'alias foreach' to existing 'foreach-list'

neosnippets/html.snip
The many of the following changes attempt to reflect best practices in writing HTML5. Recommendations from Google Lighthouse have been kept in mind as well.
* Changes the base `html5` snippet to
- Set lowercase HTML5 `doctype` since it doesn’t need to be uppercase
- Set document language (default: `en`)
- Set the `viewport` meta with a good default
* Changes the `header` snippet to use the `<header>` element
* Changes the `main` snippet to use the `<main>` element
* Changes the `footer` snippet to use the `<footer>` element
* Changes `img` to include `alt` by default
* Changes `ahref_blank` to include `rel="noopener"` by default
* Removes unnecessary self closing slashes from `br` and `hr`
* Removes unnecessary `type` from `link`/`stylesheet`/`style`
* Removes unnecessary `type` from …
=> Improve HTML snippets for HTML5 + best practices

neosnippets/python.snip
**problem**  
current `class` and `classd` snippet for python provides like below, which causes pep8/E301(expected 1 blank line, found 0).
```python
class C(object):
def __init__(self, ...)
```
**changes**  
- added blank line before `def __init__` for `class` and `classd` snippets
=> fix: add an empty line to follow PEP8/E301

neosnippets/tex.snip
I've added the aligned command from the amsmath package to the tex snippets. I prefer this style of aligning over align and align*.
=> Add aligned command from amsmath

neosnippets/tex.snip
The tex minipage snippet is missing the required width argument.
This PR adds an additional placeholder for the faction of the `\linewidth`, which is arguably the most common use case. The placeholder defaults to `0.45` which allow for 2 columns.
=> Fix missing argument in tex minipage

neosnippets/css.snip
Adding regex so CSS properties will only appear in certain contexts.
For instance, `backrepeat` will work in these contexts:
```css
div {
backrepeat
```
```css
div { backrepeat
```
```css
div {
color: blue; backrepeat
```
but not in these contexts:
```css
div backrepeat{
color: backrepeat
```
```css
div backrepeat
```
=> Only allow CSS property snippets after only whitespace or after a semicolon or open brace

neosnippets/ada.snip, neosnippets/cpp.snip, neosnippets/erlang.snip, neosnippets/php.snip, neosnippets/rst.snip, neosnippets/twig.snip
At present deoppet (Shougo/deoppet.nvim@a43cdab0fb3323dc4c12c3f0fcb858973bbb6622) raises parse error if a snippet has both of hard and soft tabs.
=> Fix snippet indentation and syntax

neosnippets/java.snip
When I code in vim I sometimes miss the println/printf shortcuts
from IntelliJ.
=> Java: Adding Alias for println() and adding printf()

neosnippets/python.snip
Using pdb inside a PyQt application implies to remove the PyQt input
hook before calling pdb.set_trace()
=> Python: pdb for PyQt application

neosnippets/c.snip, neosnippets/cpp.snip
The parameter argv of main with type 'char const * []' is incompatible
with libc getopt() and long variants, which expects a 'char * const []'.
Hence, we only have to getopt()-compatible variants for the type of
argv:
1. char * []
2. char * const []
Variant 1 is the one mentioned in the ISO C99 standard (§5.1.2.2.1) and
is the one used by the man page of getopt() or by cppreference.com on
the main function.
=> c,cpp: Remove const from argv of main

neosnippets/asciidoc.snip
Probably 'title' is a suggestive alternative to 'doc' to set the
document title.
=> asciidoc: Add title alias to doc

neosnippets/tex.snip
The majority of tikzpicture environments are part of a figure
environment, so there should be a combined snippet to add tikz-based
figures. The snippet text is a blending of the existing snippet texts of
figure and tikzpicture.
=> tex: Add snippet for tikz-based figures

neosnippets/c.snip
Making the `#include` consistent across C and CPP snippet. 
- Added a `${0}` target like CPP https://github.com/Shougo/neosnippet-snippets/blob/1315d10e60bd93483aaac4cc5a1623d13aede504/neosnippets/cpp.snip#L3-L12
=> Complete out of #includes in C

neosnippets/go.snip
This PR adds a snippet for Go fuzzing ([tutorial](https://go.dev/doc/tutorial/fuzz), [docs](https://pkg.go.dev/testing#F), [official usages](https://github.com/golang/go/search?q=%22f.Fuzz%28func%28%22)), also fixes the test snippet.
=> go: Add funcfuzz snippet
