neosnippets/elixir.snip

Elixir snippets

---

neosnippets/vimspec.snip

Add themis snippets

---

neosnippets/html.snip

Adds a «html5» snippet for quickly creating a html5 skeleton

Add a html5 snippet

---

neosnippets/ruby.snip

Update ruby snippet

---

neosnippets/_.snip

change filename to basename
add filename for file with absolute path
add path for folder absolute path

adds some globals and changes filename to basename

---

neosnippets/cs.snip

Added a snip file for flitype 'cs'

Added csharp snippet

---

neosnippets/cs.snip

and Fixed wrong try-catch syntaxes in cs.snip.
sorry, I found issue in my previous pull request.
I fixed it.

Fixed snippets circulation in cs.snip

---

neosnippets/cs.snip

I'm sorry, repeatedly...
I found problems in cs.snip
and fixed it.
And added abbr.
thanks...!!

Fixed all bugs, and added abbr on cs.snip

---

neosnippets/erlang.snip

* bs to insert binary strings easily
* case to insert pattern matches

Add a couple of erlang snippets

---

neosnippets/ada.snip

Litteral translation of Ada [vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/ada.snippets) in neosnippet compatible format, without annotations.

Add snippets for Ada

---

neosnippets/rust.snip

1. Remove redundant space of match
2. Add "derive" attribute

Update Rust snippet

---

neosnippets/javascript.snip

I needed more JS `console` members, so I added them with aliases.

Adds additional console member functions

---

neosnippets/fortran.snip

This includes a couple of basic fortran snippets. There aren't many sources of fortran snippets for vim out there. The best one I found is https://github.com/hellolife/Vim which was the basis for this file.

added fortran snippet

---

neosnippets/go.snip

Ref: http://golang.org/pkg/builtin/

Add Golang snippets of Build-in functions.

---

neosnippets/java.snip

- Fixed 'args' argument (syntax error)
- Added class definition using its file name (Java requires the same
class name as its file name)

Fixed and improved 'main' snippet for Java

---

neosnippets/ocaml.snip

* allow fun to surround
* add begin/end snippet

Improve OCaml snippets

---

neosnippets/ocaml.snip

Fix typo in try snippet

---

neosnippets/ocaml.snip

Add ocaml snippet

---

neosnippets/neosnippet.snip

Simplifying process of snippets creation.

Add more snippets to neosnippet.snip

---

neosnippets/typescript.snip

Update snippet of TypeScript.

---

neosnippets/javascript.snip

Added `while`, `switch` and `try-catch[-finally]` snippets of JavScript.

Update JavaScript snippet.

---

neosnippets/bib.snip
neosnippets/python.snip
neosnippets/tex.snip

bib.snip: fix place holders
tex.snip: fix figure snippet and add snippets for math
* fix option of includegraphics in figure
* \frac and \left \right are implemented
python.snip: rename fileidiom to with_open and update
* rename filename to file
* change mode to r (default)

update snippets of bib, tex, and python

---

neosnippets/java.snip

add some options ,let java.snip works better

add some options

---

neosnippets/elm.snip

Snippets for Elm.
http://elm-lang.org/

Add elm.snip

---

neosnippets/elm.snip

Sorry :bow:
I've misunderstood the syntax of snip file.
And I should have tested well...
In addition, while trying to use it,
I found a space should not be placed right after `=`
because we often add a newline.
And added other enhancements which I felt should be added.
Thanks for great plugin!

Fix elm.snip

---

neosnippets/verilog.snip

Fix case() snippet and add more snippets

Improve verilog snippets

---

neosnippets/javascript.snip

thought this would be useful...

added debugger snippet

---

neosnippets/php.snip

Fix 'doc' snippet for php

---

neosnippets/javascript.snip

this drove me nuts...had to fix it

fixed spacing inconsistancy

---

neosnippets/javascript.snip

Also added console log version

Added JS JSON.stringify(TARGET, null, 2) snippet

---

neosnippets/swift.snip

This pull-req contains some basic snippets for Apple Swift.

Add swift support.

---

neosnippets/scala.snip

Just a simple completion on `case`.

Implement Scala `case` snippet

---

neosnippets/twig.snip

Twig snippets for the latest version of Twig.

Add Twig snippets

---

neosnippets/ocaml.snip

* Use TARGET where appropriate
* Use correct index
* Add new `[@@deriving ..]` snippet

Fixup OCaml snippets

---

neosnippets/vim/vital.snip

0. Add `vital#{plugin-name}#new()` snippet
0. Remove `vital#of({plugin-name})` snippet
0. Fix `vital_import_without_let` snippet

Improve vital.snip

---

neosnippets/go.snip

Hi, I added some snippets that for test and benchmark. Please review it.

Add Bench* and Test* snippets to go.snip

---

neosnippets/elixir.snip

There is already `test` snippet, so we also want to include `describe`.

Add `describe` snippet to Elixir

---

neosnippets/rust.snip

There might be a better way of doing this, I'm not sure. Also is `impl-` a good name or is something like `implfor` better?

Added Impl and Trait snippets for rust.

---

neosnippets/blade.snip

I added Laravel Blade snippets.

Blade snippets added

---

neosnippets/html.snip

http://www.htmq.com/html5/003.shtml

html.snip: use HTML5 style charset

---

neosnippets/vue.snip

Move vue.snip file to neosnippets and fix missing paren.

Fix problem of vue.js support.

---

neosnippets/elm.snip

Hi,
A few of these snippets have been incompatible with the latest version of elm for a long time. This pull request updates the snippets, and updates the layout to match the popular `elm-format` formatter.
Thanks,
Toby

Update elm snippets to current version of elm

---

neosnippets/nim.snip

Add snippet for Nim-lang forked by python.snip

Add nim.snip forked by python.snip

---

neosnippets/twig.snip

Fix typo from $ to %

---

neosnippets/tex.snip

convert softtab to hardtab for proper indentation

convert softtab to hardtab

---

neosnippets/twig.snip

Added a couple snippets I use heavily working with [Timber](https://www.upstatement.com/timber/) and twig.
I also noticed a couple typos in existing snippets and patched those up.

Twig additions & bugfixes

---

neosnippets/gnuplot.snip

Added snippets for the plotting tool [Gnuplot](http://www.gnuplot.info/).

Added snippets for Gnuplot.

---

neosnippets/c.snip

Reordering some of the snipppets for c.
Created new snippets for the C11-standard operators _Static_assert and
_Genecic.
Added fori, fwrite and fread and other simple snippets.

Some snippets for C11 and reordering

---

neosnippets/javascript.snip

In many cases, let is recommended.

Fix var to let in js snippet

---

neosnippets/prolog.snip

Add snippet for `filetype=prolog`.

Add prolog snippet

---

neosnippets/go.snip

[TableDrivenTests · golang/go Wiki](https://github.com/golang/go/wiki/TableDrivenTests)

add TableDrivenTests in go snippets.

---

neosnippets/cuda.snip

Inspired by https://github.com/honza/vim-snippets/blob/master/snippets/cuda.snippets

Allow cuda files to use cpp snippets

---

neosnippets/beancount.snip

Beancount (http://furius.ca/beancount/) snippets for the following entries:
- open account
- close account
- commodity declaration
- simple transaction
- balance
- pad

Add beancount.snip

---

neosnippets/python.snip

PUDB is also a pretty popular debugger for python https://github.com/inducer/pudb and I think it should be considered in the defaults.

Add snippet for pudb

---

neosnippets/java.snip

Hi,
I just learn Java,and this code is often used.

Added setter and getter in java.snip

---

neosnippets/asciidoc.snip
neosnippets/asciidoctor.snip

* Fix backtick escaping
* New aliases
* New snippets

Asciidoc updates
